[package]
name = "nu-host"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "nu"
path = "src/main.rs"

[dependencies]
nu-cmd-lang = { path = "../nushell/crates/nu-cmd-lang", default-features = false }
nu-command = { path = "../nushell/crates/nu-command", default-features = false, features = ["which"] }
nu-engine = { path = "../nushell/crates/nu-engine", default-features = false }
nu-parser = { path = "../nushell/crates/nu-parser", default-features = false }
nu-protocol = { path = "../nushell/crates/nu-protocol", default-features = false }

